import { Footer, Navbar } from './components'
import './globals.css'
import { Inter } from 'next/font/google'
import { StateContext } from './context/StateContext'
import {Toaster} from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecommerce Site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StateContext>
      <body className={inter.className}>
        <div className='layout'>
          <Toaster/>
          <Navbar />
          <main className='main-container'>
            {children}
          </main>
          <Footer />
        </div>
      </body> 
      </StateContext>
    </html>
  )
}
